### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by ahzia**
This is the last project of the Bookstore website. I add styling to different parts of the website.
Kindly Review it and share Your Feedback with me

### CODE REVIEW

**Review by afanimartin — CHANGES_REQUESTED** [review]
Hi @lily-coder, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [x] Your design doesn't quite look like the given mockup. Please take note of the following sections of the design.
       --> vertically align the avatar, the list of books and `ADD BOOK` button
       --> the horizontal line should be less thick like in the given design. Do the same for the vertical divide between the current chapter the progress
       --> the `ADD BOOK` button needs to be vertically aligned with the list of books
       --> follow the given font in the design. The title `Bookstore CMS` should be the same font as the given mockup. Do the same for the `Books` (not `Books List`) and `Categories` nav items.

#### Refer to the original design
main-ui


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

### Martin Afani
#### Slack: whiz25

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ahzia** [comment]
@afanimartin Thanks for Reviewing, I Implemented all feedback.
Note: there are some small differences between the original design and my project which don't affect the look and as the deadline is near so There is no time to work on it.

**Review by Dipeshtwis — APPROVED** [review]
# Hi @ahzia, 

### Status: Approved ✔️

:+1: You have implemented all the suggestions made by the previous reviewer. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- The `Add new book` section needs to cover more space. You can achieve this by giving the `flex` and `space-around` style to div.

Screenshot from 2021-10-10 02-49-52


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Dipesh Kumar_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ahzia** [comment]
@Dipeshtwis Thanks for Review

**Pull request merged**
