### PR TITLE
Connect api

### PR DESCRIPTION
**Pull request by ahzia**
In this project, I connect the React-Redux application to an existing API to create and remove books on a remote server.
I used middleware to gave redux the ability to execute async code and request to the server.
Kindley Review it and Share Your Feedback With me.
Thanks

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
Hi @ahzia , 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [x] I could not start your app. it is throwing the following error. kindly fix it.
  scrnli_10_9_2021_2-56-35 PM


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [x] N/A

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by ahzia** [comment]
@rukundoeric Thanks for the Review the issue was created while I was solving linters issue, I fixed the issue.

**Review by rukundoeric — APPROVED** [review]
Hi @ahzia,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by ahzia** [comment]
@rukundoeric Thanks for reviwing.

**Pull request merged**
